### ISSUE TITLE
My Day Planner doesn't react at all to keys "Shift" either "Crl" key.

### ISSUE THREAD

**Issue by DHERRADOR** [ivan-lednev/obsidian-day-planner#464] opened 2024-05-27 11:07 UTC
After to see a video of how works your plugin, I see I can't use the functions implemented in these release.
https://github.com/ivan-lednev/obsidian-day-planner/releases/tag/0.10.0
My Day Planner doesn't react at all to keys "Shift" either "Crl" key.

I've tried to disable all of my plugins, except Day Planner and Dataview, and I can't get that Day Planner change the "mode" when I press these two keys.

**Comment by ivan-lednev** [comment] 2024-06-03 15:37
Closing this as a duplicate of #462. It explains why this behavior has changed. You can also add a comment about a more usable implementation there.

**Closed as completed by ivan-lednev** 2024-06-03 15:37 UTC
Labels: bug
