### ISSUE TITLE
Strip out time stamps in display

### ISSUE THREAD

**Issue by pianoman723** [ivan-lednev/obsidian-day-planner#648] opened 2024-11-26 23:10 UTC
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Issues](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar feature requests.
- [X] I am only requesting a single feature. Multiple changes should be split into individual requests, with links between them.
- [X] I believe my requested feature will be generally applicable to other users, not just me: it is not uniquely tied to my personal workflow.

### 🔖 Feature description

Due to limited space available in the sidebar widget, I would love the option for Day Planner to strip out the time stamps and tags from task blocks. Scheduled date, time stamp, and #task tag is all superfluous information that I'd rather hide. It should be said, I'm not just pulling tasks from daily notes, most of my tasks are from project notes, pulled in by a Dataview query on #task.

![{535FA581-65AC-4E8F-BDD3-FEFB4DED6306}](https://github.com/user-attachments/assets/2261362d-67b8-437e-9bed-7982cf6963c6)

### ✔️ Solution

As stated above, I'd like an option to remove superfluous information (scheduled date, time code, tags) from task lines.

### ❓ Alternatives

I know I can zoom in further, but I like to be able to see the whole day at a time, and the auto-scroll doesn't work well when I want to edit something later in the day.

**Comment by ivan-lednev** [comment] 2024-11-28 09:10
Duplicate of #536

**Closed as completed by ivan-lednev** 2024-11-28 09:10 UTC
Labels: enhancement

**Comment by pianoman723** [comment] 2024-11-28 11:14
Thanks Ivan, sorry I didn't catch that there was a similar issue out there. I've never even seen the Decoration toggle, I guess you took it out while you're working on it. I'm wondering though if you could add the other issues as well about the dates and the tags?
