### ISSUE TITLE
Task timeline display error; daylight savings 

### ISSUE THREAD

**Issue by MatthCapps** [ivan-lednev/obsidian-day-planner#391] opened 2024-03-10 18:45 UTC
**Describe the bug**
When creating a new task, the task displays in the planner timeline one hour ahead of the time specified in the task. 

If I had to guess, I'd say it is associated with daylight savings. 

**To Reproduce**
1. Go to your daily planning note.
2. Enter a new task with a time specified
3. Open the day planner. 
4. See the task displayed one hour ahead.

**Expected behavior**
The task should display in the timeline at the time specified in the task.

**Screenshots**
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/66439679/d8e287aa-b064-45b8-bc5b-eadb2e8b2bc8)
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/66439679/e51021a7-4b39-499c-9c14-af207e8772c5)

**Comment by nandanmv** [comment] 2024-03-11 02:58
This is happening to me too. If I drag anywhere it moves the task one hour later in the timeline.

**Comment by ivan-lednev** [comment] 2024-03-17 09:39
Closing this as a duplicate of #309.

**Closed as completed by ivan-lednev** 2024-03-17 09:39 UTC
Labels: bug
