### ISSUE TITLE
Unable to create tasks other than today with "Daily Notes"

### ISSUE THREAD

**Issue by uvsankar** [ivan-lednev/obsidian-day-planner#342] opened 2024-01-02 03:15 UTC
**Describe the bug**
 I'm using the core "Daily Notes" plugin. I modified the date format such that only one file will be created for a week. When I create a task on any day except today I'm getting an error "unable to create a new file" 

**To Reproduce**
1. Enable "Daily Notes"
2. Open "Daily Notes" settings and change "Date Format" to "ww-MMM"
3. Open the day planner and create a task for tomorrow
4. You will get the error "unable to create a new file"

**Expected behavior**
  I want the tasks added to the same file created for the week. 

**Additional context**
- OS: Mac Ventura 13.6.1 
- Obsidian version : 1.5.3
- Day planner version: 0.16.0

**Comment by ivan-lednev** [comment] 2024-10-27 17:24
This is not a bug, but a duplicate of this feature request: #374

**Closed as completed by ivan-lednev** 2024-10-27 17:24 UTC
Labels: bug
