### ISSUE TITLE
Show sub-items with time header in calendar

### ISSUE THREAD

**Issue by yoghurtdewdew** [ivan-lednev/obsidian-day-planner#287] opened 2023-10-19 07:16 UTC
I would love to use a lot of tags in parents nodes.

I wanna children nodes to be rendered as time block, too. Hope there will be more options in calendar view!

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/63794438/479b27be-b621-43da-8503-a2c918b78128)

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/63794438/44b2aa13-6e96-4edf-97b2-dd063b1dc3e1)

Related https://github.com/ivan-lednev/obsidian-day-planner/issues/251#issuecomment-1727828754

**Comment by ivan-lednev** [comment] 2023-10-19 08:27
This is a duplicate of #251, and it's been implemented. To make the sub-items show up, add checkboxes to them (`- [ ] 10:00 task`)

**Closed as completed by ivan-lednev** 2023-10-19 08:27 UTC

**Comment by yoghurtdewdew** [comment] 2023-10-19 11:11
It is great to see them separately. But I'm sorry to see no details/description with time header under the parent item.

<img width="1040" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/63794438/2c2efa9b-e873-441d-9713-ae46e48352d3">
