### ISSUE TITLE
[Feature Request] Month View 

### ISSUE THREAD

**Issue by fvnky07** [ivan-lednev/obsidian-day-planner#509] opened 2024-08-02 13:20 UTC
Hello I'm not sure the scope of this request but I'd love to see a Month view implemented to better visualise a busy month. Thanks!

Due to the limited space maybe you could do the first, middle and last tasks of the day as bullet points and then display the all day tasks on top.
![image](https://github.com/user-attachments/assets/678de4d2-e2aa-46f3-91ac-ee08eb4cca2e)

**Comment by ivan-liadniou-epam** [comment] 2024-09-02 15:28
Duplicate of #336

**Closed as completed by ivan-liadniou-epam** 2024-09-02 15:28 UTC
