### ISSUE TITLE
How to create a task in the format of unorderd list?

### ISSUE THREAD

**Issue by liangyuzou** [ivan-lednev/obsidian-day-planner#321] opened 2023-11-14 13:07 UTC
1. I tried to create some tasks in the format of unordered list like the demo of Basic editing, but the tasks in the format of unorderd list didn't appear in the timeline.

```
- [ ] 19:20 - 20:30 New item 1
- [ ] 21:10 - 22:10 New item 2
- 22:10 - 23:10 New item 3
```
<img width="1054" alt="pic1" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/146601827/3500fe8b-c36e-4c54-8336-5104875b86dc">

2. When I click to create a new task, it always creates a task in the format of to do list, how can I create a task in the format of unordered list      like in the demo of Basic editing by clicking?

Day Planner version: 0.15.3

**Comment by yodaliu0414** [comment] 2023-11-30 05:58
I met the same problem and after searching I think #282 explain this problem well. This version couldn't render the unordered list now.

**Comment by ivan-lednev** [comment] 2024-02-18 20:27
Closing this one as a duplicate of #282

**Closed as completed by ivan-lednev** 2024-02-18 20:27 UTC
