### ISSUE TITLE
Timeline drag and drop automatically shifts one hour back

### ISSUE THREAD

**Issue by MatthCapps** [ivan-lednev/obsidian-day-planner#612] opened 2024-11-03 20:27 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

Drag a task onto the timeline and have it land and stick there. 

### Current behaviour

Drag a task onto the timeline, drop, and it automatically moves one hour back, but the correct time (the time I intended to drag it to) is added to the front of the task text. The "change saved. undo" dialogue appears.

So, e.g. I drag "task" onto the timeline for 10:00-10:30, that time is added to the front of the task "10:00-10:30 task" but the card automatically jumps back one hour to 09:00 on the timeline.

### Steps to reproduce

The only thing I did differently before this started was installing the latest update (along with the updates for a few other plugins). It has also been acting weird with the chronological reorder feature, which I turned off (seems to insert a backslash into my note links, provided an example of this seemingly separate issue in the final screenshot). 

![image](https://github.com/user-attachments/assets/5f0400a2-f4c1-4760-8949-a52fea357775)
![image](https://github.com/user-attachments/assets/d1cdd6c3-3776-463e-97bd-08ddc48a75b7)
![image](https://github.com/user-attachments/assets/b86ed41e-89bb-4327-a09b-5a96e2acbd81)
![image](https://github.com/user-attachments/assets/39ae9ec8-c570-4889-90ca-7f542a34f01b)
![image](https://github.com/user-attachments/assets/8f08feab-20e7-40c1-991d-094cb7b30e53)
![image](https://github.com/user-attachments/assets/4a541a30-af82-460a-9af6-adcac8783ea4)
![image](https://github.com/user-attachments/assets/f7db8c08-c69e-4ef4-8362-bac73598b2a7)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.7.4

**Comment by MatthCapps** [comment] 2024-11-03 20:28
I did also try disabling all other plugins except minimal theme and dataview, and opening and closing Obsidian, which didn't have an effect.

**Comment by ivan-lednev** [comment] 2024-11-04 09:08
@MatthCapps, let me guess: in your timezone a shift to daylight savings time happened on the day you saw the issue, didn't it?

In that case, closing this as a duplicate: #309 

Please reload the plugin and check again. If the issue is there, respond here.

**Closed as completed by ivan-lednev** 2024-11-04 09:08 UTC
Labels: bug

**Comment by MatthCapps** [comment] 2024-11-04 14:07
It's working again. Thanks!
