### ISSUE TITLE
[Feature request] Add the option to start the week from other day (sunday)

### ISSUE THREAD

**Issue by michael-gabbay** [ivan-lednev/obsidian-day-planner#482] opened 2024-06-16 07:14 UTC
**Describe the bug**
In some places the 1st day of week is sunday and not monday, 
therefore it will be very useful in weekly planner to consider it and allow to pick the 1st day of week

**To Reproduce**
N/A

**Expected behavior**
Setting to change the 1st day of week, 
once changed to sunday, weekly planner will show the week from sunday to saturday

Thanks for this great plugin!!

**Comment by ivan-lednev** [comment] 2024-07-28 10:45
Duplicate of #231

**Closed as completed by ivan-lednev** 2024-07-28 10:45 UTC
Labels: bug
