### ISSUE TITLE
[Feature Request] Command to create new task that starts at current time

### ISSUE THREAD

**Issue by benjwu2** [ivan-lednev/obsidian-day-planner#414] opened 2024-04-04 17:40 UTC
*FR description*

A hotkey that when pressed, creates a new task on the timeline that starts at the current time.

**Comment by ivan-lednev** [comment] 2024-11-03 11:49
Seems that you're trying to achieve some kind of time tracking. Hence, closing this as a duplicate of #330

**Closed as completed by ivan-lednev** 2024-11-03 11:49 UTC
