### ISSUE TITLE
Search only for timestamps under a specific heading

### ISSUE THREAD

**Issue by jacks935** [ivan-lednev/obsidian-day-planner#589] opened 2024-10-09 08:57 UTC
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Issues](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar feature requests.
- [X] I am only requesting a single feature. Multiple changes should be split into individual requests, with links between them.
- [X] I believe my requested feature will be generally applicable to other users, not just me: it is not uniquely tied to my personal workflow.

### 🔖 Feature description

In my journal, there are two headings ("Heading 1" and "Heading 2"), both with time-attached content. However, I only want the day planner to summarize the events or tasks recorded under "Heading 1".
Because I use "Heading 1" to record the time occupied by everyday things, and under "Heading 2" I use it to record temporary thoughts and inspirations, I don't want to be counted in the chart.

### ✔️ Solution

Add a function: limit the search under a certain heading, and only display the items under this heading in the picture

**Comment by paulswail** [comment] 2024-10-15 09:42
I second this feature request, and IMO it should already be the default behaviour if the user has set a value for the "Planner Heading Text" setting.
I have a similar workflow as the OP and having any timestamp I add anywhere in my daily note treated as a time-block in the day planner is very frustrating.
A past release introduced a more global search for timestamps at the start of a line, and I had resorted to the workaround of adding an "x" before timestamped line. But it seems that the latest release now searches the entire line not just the start of it for a timestamp, and I have no way of opting out of this.

Regarding a specific implementation, I suggest a checkbox named "Only show timestamps under planner heading" in the Planner Heading section of the settings.

**Comment by ivan-lednev** [comment] 2024-10-15 11:39
This is a duplicate of #382

**Closed as completed by ivan-lednev** 2024-10-15 11:39 UTC
Labels: enhancement
