### ISSUE TITLE
[FEATURE] Track time spent on non-scheduled task

### ISSUE THREAD

**Issue by aurelienpierre** [ivan-lednev/obsidian-day-planner#153] opened 2022-04-01 15:29 UTC
The current logic of the plugin is to map a time slot with a task, so you are to switch tasks depending on time of day.

I'm working in R&D on tasks that need to be completed ASAP but it's usually hard to predict how much time they will need and certainly not desirable to hop on between tasks.

I would like to be able to declare tasks without time schedule, for example with a dummy time marker  `XX:XX` like:

```
- [ ] XX:XX Debug issue #0000
```
then start a timer on the task to record the time it took until completion. Such tasks could spread over several days. 

Then, possibly, have a table of all individual tasks with aggregated time spent over all days.

If the principle is accepted, I can try to work on that myself.

**Comment by ivan-lednev** [comment] 2024-03-17 20:13
The feature described here is a time tracker like Toggl. Closing this as a duplicate of #330.

**Closed by ivan-lednev** 2024-03-17 20:13 UTC
Labels: enhancement
