### ISSUE TITLE
Plugin not accounting for Daylight Saving Time in the United States

### ISSUE THREAD

**Issue by TomBirkland** [ivan-lednev/obsidian-day-planner#390] opened 2024-03-10 17:05 UTC
Love this plugin, and am starting to use it more intensively because it's so helpful. But with the change to daylight saving time in the United States, the plugin does not properly behave. If I add a task to occur, say, between 13:00 and 14:00 today, it will show on the day planner at running from 1200 to 1300. I can work around this but it's not ideal. I hope this is helpful--I am not a programmer so let me know if this is insufficient information.

**Comment by ivan-lednev** [comment] 2024-03-10 17:24
Hello, @TomBirkland! This is a known issue, and it happens only on the day when the time gets changed. If this happens on any other day, please re-open this issue. Closing it as a duplicate of #309 for now.

**Closed as completed by ivan-lednev** 2024-03-10 17:24 UTC
Labels: bug

**Comment by TomBirkland** [comment] 2024-03-10 17:49
Thank you!

**Comment by fleeflonc** [comment] 2025-03-10 00:31
Is there an actual way to resolve this? I've reloaded both the plugin and obsidian and the issue persists. if the answer is really just "you have to wait until tomorrow" i really think this deserves attention. this has completely thrown my ability to schedule and plan with this tool today, and I can't find any answer as to whether this is resolvable without simply waiting until tomorrow.
