### ISSUE TITLE
A Timeline Bug and Console error

### ISSUE THREAD

**Issue by Kang-geophysics** [ivan-lednev/obsidian-day-planner#372] opened 2024-02-23 01:38 UTC
Thank you for your efforts.

**Describe the bug**
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/56065588/45108c3b-3265-4c94-acbe-189a8285a750)
- I use Day planner with daily note. (Not periodic note)
- I added dataview source to filter tasks generated by tasks-plugin.
- "Tasks" generated by the plugin are shown in timeline, but the lists in daily note are not shown in time line. 
- This issue seems to be solved when I reload Obsidian. However this kind of problem happens again and again.

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/56065588/b0a81bb8-ea3d-49a1-a284-f57390c14079)
- This is console error.
- When I open Obsidian, this console error occurs.
- Is this console error related with Time line bug?
- Why the lists in daily note are not shown in time line?

Why this error occurs ?

Obsidian version: 1.5.8
day planner version: 0.18.0

**Comment by ivan-lednev** [comment] 2024-03-10 09:09
Please update and re-check.

For now, closing this one as a duplicate of #384.

**Closed as completed by ivan-lednev** 2024-03-10 09:09 UTC
Labels: bug
