### ISSUE TITLE
Event and Tasks outside Day Planner session added in Timeline

### ISSUE THREAD

**Issue by annefortesting** [ivan-lednev/obsidian-day-planner#487] opened 2024-06-22 15:33 UTC
**Describe the bug**
When a task or an event is added on a daily page outside the day planner section, I don't expect them to be seen on the Day Planner Timeline

**To Reproduce**
1. Go to Community Plugin, install, enable and configure dataview, calendar, periodic notes and day planner plguins
2. Open Day Planner timeline, select a day and create an event (let's say at 10:00)
3. Open the day page to confirm the dayplanner section is created and the event is seen
4. Above Day Planner Section, add another event, at another time of the day >> the event is seen on the day planner timeline (not expected)
5. Below Day planner section, create a new section by adding a new headline and create a task or an event : they are seen on dayplanner timeline (not expected)

7. See error

**Expected behavior**
Task and event outside Day Planner defined section shouldn't be seen on the Day Planner Timeline (or week view)

**Screenshots**
<img width="1031" alt="Screenshot 2024-06-22 at 17 31 42" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/47664601/2fa55073-68de-4a42-82bf-af4915259e01">

**Additional context**

**Comment by ivan-lednev** [comment] 2024-06-28 16:37
This is a duplicate of #382

**Closed as completed by ivan-lednev** 2024-06-28 16:37 UTC
Labels: bug
