### ISSUE TITLE
Day Planner is ruining the format of future daily notes

### ISSUE THREAD

**Issue by Michael679089** [ivan-lednev/obsidian-day-planner#633] opened 2024-11-18 09:18 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

I expect that day planner will create a future date daily note with the task that I put be in that note.

So I can be reminded of that task in the future.

### Current behaviour

![image](https://github.com/user-attachments/assets/e0e06857-c2ea-4ae4-ab93-beec9c8cd906)

why is day planner replacing dashes with ***

it breaks the format of my daily notes.

### Steps to reproduce

- create task in day planner in future date (it breaks both with the future date daily note create and not created).
- Boom, it just breaks the format of the journal.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.7.6

### Possible solution

Disable Day Planner in replacing:
--- to ***

also stop adding random slashes at the start of ---

**Comment by ivan-lednev** [comment] 2024-11-18 10:24
Duplicate of #625

**Closed as completed by ivan-lednev** 2024-11-18 10:24 UTC
Labels: bug
