### ISSUE TITLE
Day planner freezes after moving the task in timeline view 

### ISSUE THREAD

**Issue by Vlislavn** [ivan-lednev/obsidian-day-planner#460] opened 2024-05-15 09:55 UTC
**Describe the bug**
Day planner freezes after dragging tasks from unscheduled field to the timeline if the task is from another note (not a daily note)

**To Reproduce**
1. Change dataview source to filter `-"#backlog"` (i.e all tasks) 
2. move in timeline an unscheduled task (located in daily note from other date, but have scheduled date today. Task has no time 
3. no other tasks can be moved in the timeline 

```
plugin:obsidian-day-planner:48325 Uncaught TypeError: Cannot read properties of undefined (reading 'noTime')
    at removeTask (plugin:obsidian-day-planner:48325:19)
    at moveTaskToDay (plugin:obsidian-day-planner:48349:18)
    at moveTaskToColumn (plugin:obsidian-day-planner:48361:10)
    at transform (plugin:obsidian-day-planner:48557:33)
    at eval (plugin:obsidian-day-planner:48597:14)
    at sync (plugin:obsidian-day-planner:34525:22)
    at Array.eval (plugin:obsidian-day-planner:34536:9)
    at Object.set2 [as set] (plugin:obsidian-day-planner:34484:35)
    at startEdit (plugin:obsidian-day-planner:48736:19)
    at handleUnscheduledTaskGripMouseDown (plugin:obsidian-day-planner:47586:5)
    at Array.func (plugin:obsidian-day-planner:46179:26)
    at HTMLDivElement.func (plugin:obsidian-day-planner:46034:13)
    at HTMLDivElement.eval (plugin:obsidian-day-planner:45762:14)
    at eval (plugin:obsidian-day-planner:34042:42)
    at Array.forEach (<anonymous>)
    at HTMLDivElement.bubble (plugin:obsidian-day-planner:34042:23)
    at HTMLDivElement.mousedown_handler2 (plugin:obsidian-day-planner:43558:12)
    at HTMLDivElement.eval (plugin:obsidian-day-planner:33914:15)
```    
5. cured with relaunch with obsidian 

**Expected behavior**
move the task without error and assign a time if needed. currently only if I have a time before task i can move it 

**Additional context**
if the task has predifined time it works okay. 
using tasks plugin

**Comment by jderiz** [comment] 2024-06-18 09:00
same here

**Comment by burgerga** [comment] 2024-07-06 06:26
Duplicate of #421

**Closed as completed** 2024-07-08 08:38 UTC
Labels: bug
