### ISSUE TITLE
Can't disable showing time in timeline

### ISSUE THREAD

**Issue by y9san9** [ivan-lednev/obsidian-day-planner#564] opened 2024-09-20 07:28 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar reports.

### Expected Behavior

When I disable setting 'Show timestamp next to task text in timeline' it should stop showing the timestamp.

### Current behaviour

It doesn't

### Steps to reproduce

Install Plugin. Don't do anything. You will have timestamps in your timeline even though by default this setting is not enabled

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.6.7

**Comment by ivan-lednev** [comment] 2024-09-20 09:02
Duplicate of #536

**Closed as completed by ivan-lednev** 2024-09-20 09:02 UTC
Labels: bug

**Comment by y9san9** [comment] 2024-09-20 09:03
Ah, I didn't find it. Sorry for duplicate.
