### ISSUE TITLE
iOS: timeline refresh button doesn't work; settings don't get saved

### ISSUE THREAD

**Issue by duxswhatdux** [ivan-lednev/obsidian-day-planner#408] opened 2024-04-01 00:19 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ivan-lednev** [comment] 2024-06-04 08:37
Hello, @duxswhatdux,

I don't have an iOS device to debug this, so marking this as `help wanted`.

**Comment by ivan-lednev** [comment] 2024-11-03 11:52
Seems like a duplicate of #519

**Closed as completed by ivan-lednev** 2024-11-03 11:52 UTC
Labels: bug, help wanted
