### ISSUE TITLE
 Feature Request: Enhanced Control Over Checkboxes in Timeline View

### ISSUE THREAD

**Issue by Kang-geophysics** [ivan-lednev/obsidian-day-planner#402] opened 2024-03-22 07:49 UTC
#### Current Behavior
As it stands, checkboxes that originate from the current daily note interaction in the timeline view doesn't matter. However, checkboxes that are derived from other source need the interaction in the timeline. To change the status of these checkboxes (e.g., marking a task as completed), one must navigate away from the timeline view to the original note where the checkbox is located. This process introduces unnecessary friction and disrupts the flow of managing tasks efficiently across different notes within the timeline view.

#### Suggested Feature
I propose the development of a feature that enables users to change the status of any checkbox directly from the timeline view. This enhancement would allow for a more unified and efficient task management experience, as users could interact with tasks derived from various notes without the need to navigate away from the timeline.

Thank you very much.

**Comment by ivan-lednev** [comment] 2024-03-22 10:15
Hello, @Kang-geophysics!

This is a duplicate of #304. 

In the meantime, you can use the hover-editor plugin to complete tasks quickly by clicking on the checkbox inside the editor:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/904388a2-1bdf-434d-95e4-3a070617bb11)

**Closed as completed by ivan-lednev** 2024-03-22 10:15 UTC
