### ISSUE TITLE
Add confirmation before creating Daily Note

### ISSUE THREAD

**Issue by kachidk** [ivan-lednev/obsidian-day-planner#585] opened 2024-10-03 14:09 UTC
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Issues](https://github.com/ivan-lednev/obsidian-day-planner/issues?q=is%3Aissue+is%3Aopen) didn't find any similar feature requests.
- [X] I am only requesting a single feature. Multiple changes should be split into individual requests, with links between them.
- [X] I believe my requested feature will be generally applicable to other users, not just me: it is not uniquely tied to my personal workflow.

### 🔖 Feature description

Add confirmation before creating Daily Note

### ✔️ Solution

Add a confirmation dialog before creating a daily note

### ❓ Alternatives

None

### 📝 Additional Context

None

**Comment by ivan-lednev** [comment] 2024-10-03 14:18
Duplicate of #373

**Closed as completed by ivan-lednev** 2024-10-03 14:18 UTC
Labels: enhancement
