### ISSUE TITLE
Planner Heading Text Ignored

### ISSUE THREAD

**Issue by rvzaytsev** [ivan-lednev/obsidian-day-planner#459] opened 2024-05-14 09:17 UTC
**Describe the bug**
Day Planner is ignoring the planner heading text.

**To Reproduce**
1. Open today's daily note
2. Enter some check boxes, e.g.
 - [ ] A
 - [ ] B
3. Open the Week Planner view. Those checkboxes will appear, even though they are not under any planner heading.

**Expected behavior**
I expect that only the checkboxes under the planner heading are shown on the Timeline and the Week Planner view

**Comment by rvzaytsev** [comment] 2024-05-14 09:35
Ok, I found how to resolve it partially: in the timeline, I can click the settings icon, scroll down to unscheduled tasks, and disable them. But that doesn't exactly answer the original question. BTW, is there any documentation for this? I found that button mainly by trial and error.

**Comment by kennethtom** [comment] 2024-05-20 22:44
Relates to #382 

There is an issue with the Planner Heading settings. Please fix this bug.

**Comment by ivan-lednev** [comment] 2024-05-24 08:36
This is a duplicate of #382

**Closed as completed by ivan-lednev** 2024-05-24 08:36 UTC
Labels: bug
