### ISSUE TITLE
Inline fields get removed when rescheduling a task

### ISSUE THREAD

**Issue by mateuszkowalczyk** [ivan-lednev/obsidian-day-planner#375] opened 2024-02-26 11:14 UTC
**Describe the bug**
When I drag or resize task in Day Planner Timeline all the metadata in Dataview inline field format (https://blacksmithgu.github.io/obsidian-dataview/annotation/metadata-tasks/) gets removed

**To Reproduce**
1. Add a task with inline field(s) to Daily Note (or basically any other note if the task has scheduled date), for example:
`- [ ] Sample task [points:: 3]`
2. Schedule it to some time of the day either by dragging and dropping or manually typing hours range to get something like this:
`- [ ] 10:30 - 11:00 Sample task [points:: 3]`
3. In Timeline view drag the task to a different time or adjust its ending time (also by dragging)
4. After that, task is changed to something like this (inline field is removed):
`- [ ] 10:00 - 10:30 Sample task`

**Expected behavior**
Inline fields should remain in place unmodified

**Additional context**
The bug appeared after updating to 0.18.0 (not sure from which version exactly, but some from around 2-3 months ago). It worked fine before.

**Comment by imshenwei** [comment] 2024-03-05 15:08
#370

**Comment by ivan-lednev** [comment] 2024-03-09 14:57
Closing this as a duplicate of #370

**Closed as completed by ivan-lednev** 2024-03-09 14:57 UTC
Labels: bug
