### ISSUE TITLE
Request: Add the ability to filter out timestamps that do not belong to a task

### ISSUE THREAD

**Issue by Sammmmm** [ivan-lednev/obsidian-day-planner#472] opened 2024-06-08 11:22 UTC
If there is a way to do this with the existing filter, please let me know nothing I have tried is working.

It seems that all timestamps in the daily log, not just tasks are included in the day planner.  I would like syntax or a setting to filter out timestamps -- particularly ones not part of a a task/checkbox markdown syntax -- or a section of the daily log.

Reasoning: 
I use a quick action to capture a daily 'log' of thoughts and actions to my daily note, formatted like this:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/2768751/f1289e37-0e14-4e54-ab48-514fd1b1fd86)

I also use the day planner to add tasks

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/2768751/67be7619-58a1-4406-95a4-e908812544fa)

The issue is, the day planner treats all timestamps as tasks, even if they aren't created using the task/checkbox markdown syntax:

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/2768751/5dab01fb-da97-4890-9288-7d1d4ea311dd)

I would like a way to filter out timestamps that aren't part of a task, since these don't need to show up on my day planner as tasks and break the flow of the now/next status

**Comment by Sammmmm** [comment] 2024-06-08 13:11
It turns out anything other than time immediately preceding the bullet point breaks this pattern.. using dataview (time::11:30)  instead makes it not show up and works for me.

**Comment by ivan-lednev** [comment] 2024-07-11 13:24
Duplicate of #382

**Closed as completed by ivan-lednev** 2024-07-11 13:24 UTC
