### ISSUE TITLE
after update day planner，it cannot create dayplanner-YYMMDD file automatically

### ISSUE THREAD

**Issue by show-me-code** [ivan-lednev/obsidian-day-planner#303] opened 2023-10-30 02:55 UTC
after I update this plugin, the day planner-YYMMDD file in /Day Planners will not be updated every day.
By the way, I cannot find Daily Notes and Periodic Notes in the plugin market.
Any help would be appreciated!

**Comment by ivan-lednev** [comment] 2024-11-03 12:08
Duplicate of #242

**Closed as completed by ivan-lednev** 2024-11-03 12:08 UTC
