### ISSUE TITLE
[Feature Request] Create events only on right click

### ISSUE THREAD

**Issue by Griizz** [ivan-lednev/obsidian-day-planner#467] opened 2024-06-03 13:22 UTC
**Describe the issue**
I frequently create new events by accident, when I try to move or resize another event.

**Expected behavior**
Currently, you can create new Events with left and right click. I'd like a setting to change this behavior to right-click-only. So creating an event by accident becomes unlikely.

**Additional context**
 An analog left-click-only setting would probably make sense for others.

**Comment by ivan-lednev** [comment] 2024-06-03 15:28
Hello, @Griizz, I'm closing this as a duplicate of #341, that describes the same problem.

**Closed as completed by ivan-lednev** 2024-06-03 15:28 UTC
Labels: bug
