### ISSUE TITLE
Can you return the display of time periods without the checkbox?

### ISSUE THREAD

**Issue by westtrade** [ivan-lednev/obsidian-day-planner#329] opened 2023-11-25 16:35 UTC
This was a very convenient feature for allocating time - which is not task - in order to understand your daily busyness.

Like this

```md
- 18:30 - 19:30 Time spent at the concert

```

**Comment by ivan-lednev** [comment] 2023-11-26 10:40
This is a duplicate of #282

**Closed as completed by ivan-lednev** 2023-11-26 10:40 UTC
