### ISSUE TITLE
[ Feature Request / Bug ] Problems with admonitions

### ISSUE THREAD

**Issue by DoctorApparatus** [ivan-lednev/obsidian-day-planner#337] opened 2023-12-05 21:16 UTC
**Describe the bug**
When I'm putting the day planner syntax inside an admonition it doesn't get recognized

**To Reproduce**
`
> ###### Day planner
>
> - 06:00 - 14:30 Plus Server
> - 14:30 - 15:30 Cooking
> - 15:30 - 17:00 Programming
`

**Expected behavior**
I would expect this plugin to behave the same way with admonitions since it's a helpful way for visualizing daily notes a bit better.

**Comment by Duifkruid** [comment] 2023-12-09 17:39
Still having this problem, and linking to [issue #266](https://github.com/ivan-lednev/obsidian-day-planner/issues/266). Thanks for revisiting this Ivan!
xDuifkruid

**Comment by ivan-lednev** [comment] 2024-11-03 12:02
duplicate of #385

**Closed as completed by ivan-lednev** 2024-11-03 12:02 UTC
Labels: bug
