### ISSUE TITLE
FR Tasks in the Daily note to follow the chronologic order

### ISSUE THREAD

**Issue by sudo-saif** [ivan-lednev/obsidian-day-planner#279] opened 2023-10-13 16:49 UTC
Hello there,

Currently the tasks are created under the Day planner heading and are ordered as they're created

When I schedule them on the Planner, and for example:
Task 1 set to 1 PM
Task 2 set to 2 PM

I move task 2 to be 12:30 PM

The tasks in the daily note are still ordered like that:
Task 1 at 1 PM
Task 2 at 12:30 PM

It should be automatically ordered to:
Task 2 at 12:30 PM
Task 1 at 1 PM

**Comment by ivan-lednev** [comment] 2023-10-13 16:54
This is a duplicate of #106

**Closed as completed by ivan-lednev** 2023-10-13 16:54 UTC
