### ISSUE TITLE
Feature Request: Checking of tasks in Week Planner and Timeline

### ISSUE THREAD

**Issue by LennartCode** [ivan-lednev/obsidian-day-planner#355] opened 2024-01-22 15:16 UTC
## Description of Current Situation

Currently, tasks with checkboxes can be displayed in the week planner and timeline. They resemble the standard obsidian markdown checkboxes but are just a visual indicator for whether the task is checked off.

## Suggestion

Make the checkbox tickable (clicking modifies the note) to be consistent with the checking the user knows from markdown notes. This also eliminates the additional step of opening the note to tick off the task manually.

## Thanks :)

Thank you for your amazing, ongoing development on this fantastic project. It's a great help in daily life! <3

**Comment by ivan-lednev** [comment] 2024-03-17 20:11
Closing this as a duplicate of #304.

**Closed as completed by ivan-lednev** 2024-03-17 20:11 UTC
Labels: bug
